name: sandbox
on: [push]

jobs:
  api-call:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.workflow-check.outputs.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Get value via api call
        id: workflow-check
        uses: ./.github/actions/oktokit-example
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print value from api call
        run: echo "The value from api call is ${{ steps.workflow-check.outputs.conclusion }}"

  print-output:
    needs: api-call
    if: ${{ needs.api-call.outputs.conclusion }} == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Print output
        run: echo "The status is ${{ needs.api-call.outputs.conclusion }}"

  some-other-job:
    needs: print-output
    runs-on: ubuntu-latest
    steps:
      - name: Some step
        run: echo "Some step should not have executed"