name: sandbox
on: [push]

jobs:
  oktokit-gh-api-call:
    runs-on: ubuntu-latest
    name: Use ocktokit to make a github api call
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Get value via api call
        id: api-call
        uses: ./.github/actions/oktokit-example
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print value from api call
        run: echo "The value from api call is ${{ steps.api-call.outputs.conclusion }}"